lib/puppies_web/router.ex
defmodule PuppiesWeb.Router do
  use PuppiesWeb, :router

  import PuppiesWeb.UserAuth
  import PuppiesWeb.AdminAuth
  alias PuppiesWeb.CheckUserStatus

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {PuppiesWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:fetch_current_user)
  end

  pipeline(:session_layout) do
    plug(:put_root_layout, {PuppiesWeb.LayoutView, :session})
  end

  pipeline :check_user_status do
    plug(CheckUserStatus)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  # Other scopes may use custom stacks.
  # scope "/api", PuppiesWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through(:browser)

      live_dashboard("/dashboard", metrics: PuppiesWeb.Telemetry)
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through(:browser)

      forward("/mailbox", Plug.Swoosh.MailboxPreview)
    end
  end

  ## Authentication routes

  scope "/", PuppiesWeb do
    pipe_through([:browser, :session_layout, :redirect_if_user_is_authenticated])
    get("/users/register", UserRegistrationController, :new)
    post("/users/register", UserRegistrationController, :create)
    get("/users/log_in", UserSessionController, :new)
    post("/users/log_in", UserSessionController, :create)
    get("/users/reset_password", UserResetPasswordController, :new)
    post("/users/reset_password", UserResetPasswordController, :create)
    get("/users/reset_password/:token", UserResetPasswordController, :edit)
    put("/users/reset_password/:token", UserResetPasswordController, :update)
  end

  scope "/", PuppiesWeb do
    pipe_through([:browser, :require_authenticated_user, :check_user_status])

    # dashboard
    live("/users/dashboard", UserDashboardLive)

    # business
    live("/users/business/new", BusinessNew)
    live("/users/business/:id/edit", BusinessEdit)

    # listings
    live("/listings/new", ListingsNew)
    live("/listings/:listing_id/status", ListingsStatusUpdateForm)
    live("/listings/:listing_id/edit", ListingsEdit)

    # reviews

    live("/reviews", Reviews)
    get("/reviews/new", ReviewController, :new)
    post("/reviews/create", ReviewController, :create)
    get("/reviews/show/:id", ReviewController, :show)

    # user
    live("/users/profile", UserProfile)
    get("/users/security", UserSecurityController, :edit)
    put("/users/security", UserSecurityController, :update)
    get("/users/settings", UserSettingsController, :edit)
    post("/users/settings", UserSettingsController, :create)
    put("/users/settings", UserSettingsController, :update)
    get("/users/settings/confirm_email/:token", UserSettingsController, :confirm_email)

    # messages
    live("/messages", MessagesLive)

    # notifications
    live("/notifications", NotificationsLive)

    # plans
    live("/plans", ProductsLive)
    live("/checkout/:product", CheckoutLive)
    live("/success", CheckoutSuccessLive)

    # orders
    live("/order-history", OrderHistoryLive)
    live("/id-verification", IDVerificationLive)
    live("/verifications", VerificationsLive)
  end

  scope "/", PuppiesWeb do
    pipe_through([:browser])

    get("/", PageController, :index)

    live("/search", SearchLive)
    live("/business/:slug", BusinessPageLive)

    # breeds
    live("/breeds", BreedsIndexLive)
    live("/breeds/:slug", BreedsShowLive)
    live("/match-maker", BreedsMatchMakerLive)

    # listings
    live("/listings/:listing_id", ListingShow)

    delete("/users/log_out", UserSessionController, :delete)
    get("/users/confirm", UserConfirmationController, :new)
    post("/users/confirm", UserConfirmationController, :create)
    get("/users/confirm/:token", UserConfirmationController, :edit)
    post("/users/confirm/:token", UserConfirmationController, :update)

    get("/suspended", SuspendedController, :index)
    get("/email-not-confirmed", EmailNotConfirmedController, :index)
    get("/legal/term-of-service", LegalController, :terms_of_service)
    get("/legal/privacy", LegalController, :privacy)
    get("/contacts/new", ContactController, :new)
    post("/contacts", ContactController, :create)
    get("/faq", FaqController, :index)
    get("/sitemap.xml", SitemapController, :index)

    live("/puppies-in/:city/:state/:breed", FindPuppyLive)
    live("/puppies-in/:city/:state", FindPuppyLive)
    live("/puppies-in/:state", FindPuppyLive)
  end

  # webhooks
  scope "/stripe/webhooks", PuppiesWeb do
    post("/", StripeWebhooksController, :webhooks)
  end

  ## Admin routes

  pipeline :admin_browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {PuppiesWeb.LayoutView, :admin_root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:fetch_current_admin)
  end

  scope "/admin/", PuppiesWeb do
    pipe_through([:browser, :session_layout, :redirect_if_admin_is_authenticated])

    get("/register", AdminRegistrationController, :new)
    post("/register", AdminRegistrationController, :create)
    get("/log_in", AdminSessionController, :new)
    post("/log_in", AdminSessionController, :create)
    # get("/reset_password", AdminResetPasswordController, :new)
    # post("/reset_password", AdminResetPasswordController, :create)
    # get("/reset_password/:token", AdminResetPasswordController, :edit)
    # put("/reset_password/:token", AdminResetPasswordController, :update)
  end

  scope "/admin/", PuppiesWeb do
    pipe_through([:browser, :admin_browser, :require_authenticated_admin])

    get("/settings", AdminSettingsController, :edit)
    put("/settings", AdminSettingsController, :update)
    get("/settings/confirm_email/:token", AdminSettingsController, :confirm_email)
    live("/dashboard", Admin.Dashboard)
    live("/blacklists", Admin.BlackLists)
    live("/photo-review", Admin.PhotoReview)
    live("/user/:id", Admin.User)
  end

  scope "/admins/", PuppiesWeb do
    pipe_through([:browser])

    delete("/log_out", AdminSessionController, :delete)
  end
end

lib/puppies_web/controllers/user_session_controller.ex
defmodule PuppiesWeb.UserSessionController do
  use PuppiesWeb, :controller

  alias Puppies.{Accounts, Utilities}
  alias PuppiesWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      Puppies.BackgroundJobCoordinator.re_index_user(user.id)

      cond do
        user.status == "suspended" ->
          redirect(conn, to: Routes.suspended_path(conn, :index)) |> halt()

        user.status == "locked" ->
          Puppies.ES.Listings.re_index_listings_by_user_id(user.id)

          render(conn, "new.html",
            error_message:
              "Your account may have been compromised. Use the \"Forgot your password?\" link below to unlock account."
          )

        true ->
          ip = Utilities.x_forward_or_remote_ip(conn)

          Puppies.BackgroundJobCoordinator.session(
            user.id,
            user.first_name,
            user.last_name,
            user.email,
            ip,
            "signed in"
          )

          UserAuth.log_in_user(conn, user, user_params)
      end
    else
      # In order to prevent user enumeration attacks, don't disclose whether the email is registered.
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def delete(conn, _params) do
    user = conn.assigns.current_user
    Puppies.BackgroundJobCoordinator.logout(user)

    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end
end

lib/puppies_web/views/user_session_view.ex
defmodule PuppiesWeb.UserSessionView do
  use PuppiesWeb, :view
end

lib/puppies_web/templates/user_session/new.html.heex
<div class="min-h-full flex bg-white">
  <div class="flex-1 flex flex-col justify-center py-12 px-4 sm:px-6 lg:flex-none lg:px-20 xl:px-24">
    <div class="mx-auto w-full max-w-sm lg:w-96">
      <div>
        <%= img_tag(Routes.static_path(@conn, "/images/rr-logo-150.svg"), class: "mx-auto") %>
        <h2 class="mt-6 text-3xl font-bold text-center text-gray-900">
          Sign in to your account
        </h2>
      </div>

      <div class="mt-8">
        <div class="mt-6">
          <%= form_for @conn, Routes.user_session_path(@conn, :create), [as: :user, class: "space-y-6"], fn f -> %>
           <%= if @error_message do %>
              <div class="alert alert-danger">
                <p><%= @error_message %></p>
              </div>
            <% end %>

            <div>
              <%= label f, :email, class: "block text-sm font-medium text-gray-700" %>
              <div class="mt-1">
                <%= email_input f, :email, required: true, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm" %>
              </div>
            </div>

            <div class="space-y-1">
              <%= label f, :password, class: "block text-sm font-medium text-gray-700" %>
              <div class="mt-1">
                <%= password_input f, :password, required: true, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm" %>
              </div>
            </div>

            <div class="flex items-center justify-between">
              <div class="flex items-center">
                <%= checkbox f, :remember_me, class: "-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded" %>
                <label for="remember-me" class="ml-2 block text-sm text-gray-900">
                  Remember me
                </label>
              </div>

              <div class="text-sm">
                <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new), class: "font-medium text-primary-600 hover:text-primary-500" %>
              </div>
            </div>

            <div>
              <%= submit "Sign In", class: "w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500" %>
            </div>
            <div class='text-center' >
               <%= link "Sign Up", to: Routes.user_registration_path(@conn, :new), class: "font-medium text-primary-600 hover:text-primary-500" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="hidden lg:block relative w-0 flex-1">
    <img class="absolute inset-0 h-full w-full object-cover" src="https://images.unsplash.com/photo-1577175826207-5052ccbf89e8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fGRvZ3MlMjBodW1hbnN8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60" alt="">
  </div>
</div>